// Stub data for development when the trading gateway is not available.
// Shaped to match the validator /hl-traders/<address> response.
// To go live: remove STUB_GATEWAY=true from .env.local

export const STUB_ENABLED = process.env.STUB_GATEWAY === "true";

export const stubStatus = {
  endpoint_url: "https://stub.gateway.local",
  hl_address: "0x0000000000000000000000000000000000000000",
  status: "active",
};

export const stubDashboard = {
  status: "success",
  timestamp: Date.now(),
  // From subaccount_info
  synthetic_hotkey: "stub_hotkey_0",
  subaccount_uuid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  subaccount_id: 0,
  asset_class: "crypto",
  account_size: 10000.0,
  subaccount_status: "active",
  created_at_ms: Date.now() - 86400000 * 30,
  eliminated_at_ms: null,
  hl_address: "0x0000000000000000000000000000000000000000",
  payout_address: "0x0000000000000000000000000000000000000001",
  // Challenge period
  challenge_period: {
    bucket: "SUBACCOUNT_CHALLENGE",
    start_time_ms: Date.now() - 864000000,
  },
  // Drawdown (with computed convenience fields)
  drawdown: {
    current_equity: 1.06,
    daily_open_equity: 1.055,
    eod_hwm: 1.065,
    last_eod_equity: 1.055,
    intraday_drawdown_pct: 1.85,
    eod_drawdown_pct: 0.94,
    intraday_drawdown_threshold: 0.05,
    eod_drawdown_threshold: 0.08,
    intraday_threshold_pct: 5.0,
    eod_threshold_pct: 8.0,
    intraday_usage_pct: 37.0,
    eod_usage_pct: 11.75,
  },
  // Account size data
  account_size_data: {
    account_size: 10000.0,
    total_realized_pnl: 187.3,
    capital_used: 8000.0,
    balance: 10187.3,
    buying_power: 4687.3,
    max_return: 1.065,
  },
  // Positions (transformed from map to array)
  positions: {
    positions: [
      {
        position_uuid: "pos-uuid-1",
        trade_pair: "BTC/USD",
        position_type: "LONG",
        average_entry_price: 67500.0,
        net_leverage: 0.3,
        current_return: 1.032,
        realized_pnl: 0,
        is_closed_position: false,
        open_ms: Date.now() - 86400000 * 2,
        close_ms: null,
        return_at_close: null,
        filled_orders: [],
        unfilled_orders: [],
        fee_history: null,
      },
      {
        position_uuid: "pos-uuid-2",
        trade_pair: "ETH/USD",
        position_type: "SHORT",
        average_entry_price: 3450.0,
        net_leverage: -0.5,
        current_return: 0.986,
        realized_pnl: 0,
        is_closed_position: false,
        open_ms: Date.now() - 86400000,
        close_ms: null,
        return_at_close: null,
        filled_orders: [],
        unfilled_orders: [],
        fee_history: null,
      },
      {
        position_uuid: "pos-uuid-3",
        trade_pair: "SOL/USD",
        position_type: "FLAT",
        average_entry_price: 142.5,
        net_leverage: 0.0,
        realized_pnl: 187.3,
        current_return: 1.045,
        return_at_close: 1.045,
        is_closed_position: true,
        open_ms: Date.now() - 86400000 * 3,
        close_ms: Date.now() - 86400000,
        filled_orders: [],
        unfilled_orders: [],
        fee_history: null,
      },
      {
        position_uuid: "pos-uuid-4",
        trade_pair: "ETH/USD",
        position_type: "FLAT",
        average_entry_price: 3200.0,
        net_leverage: 0.0,
        realized_pnl: -95.0,
        current_return: 0.97,
        return_at_close: 0.97,
        is_closed_position: true,
        open_ms: Date.now() - 86400000 * 5,
        close_ms: Date.now() - 86400000 * 4,
        filled_orders: [],
        unfilled_orders: [],
        fee_history: null,
      },
    ],
    all_time_returns: 1.045,
    total_leverage: 0.8,
    positions_time_ms: Date.now(),
  },
  // Limit orders
  limit_orders: null,
  // Elimination
  elimination: null,
  // Limits (from separate endpoint, unchanged)
  limits: {
    status: "success",
    hl_address: "0x0000000000000000000000000000000000000000",
    account_size: 10000.0,
    max_position_per_pair_usd: 5000.0,
    max_portfolio_usd: 50000.0,
    in_challenge_period: true,
    timestamp: Date.now(),
  },
};

export const stubEvents = [
  {
    trade_pair: "BTC/USD",
    order_type: "LONG",
    status: "accepted",
    error_message: "",
    leverage: 0.3,
    price: 67842.5,
    size_usd: 3000,
    timestamp_ms: Date.now() - 3600000,
  },
  {
    trade_pair: "ETH/USD",
    order_type: "SHORT",
    status: "accepted",
    error_message: "",
    leverage: 0.5,
    price: 3451.2,
    size_usd: 5000,
    timestamp_ms: Date.now() - 7200000,
  },
  {
    trade_pair: "SOL/USD",
    order_type: "LONG",
    status: "rejected",
    error_message: "Insufficient margin",
    leverage: 1.2,
    price: 143.85,
    size_usd: 12000,
    timestamp_ms: Date.now() - 14400000,
  },
  {
    trade_pair: "BTC/USD",
    order_type: "SHORT",
    status: "accepted",
    error_message: "",
    leverage: 0.15,
    price: 67210.0,
    size_usd: 1500,
    timestamp_ms: Date.now() - 28800000,
  },
  {
    trade_pair: "DOGE/USD",
    order_type: "LONG",
    status: "rejected",
    error_message: "Position limit exceeded",
    leverage: 2.0,
    price: 0.1483,
    size_usd: 8000,
    timestamp_ms: Date.now() - 43200000,
  },
];
